apiVersion: v2
name: tracing-app
description: Helm chart for deploying the agyn Tracing App.
type: application
version: 0.1.0
appVersion: 0.1.0
home: https://github.com/agynio/tracing-app
sources:
  - https://github.com/agynio/tracing-app
dependencies:
  - name: service-base
    version: ">=0.1.4 <1.0.0"
    repository: oci://ghcr.io/agynio/charts
